### ISSUE TITLE
Add keybinding to open selected file/folder without mouse

### ISSUE THREAD

**Issue by lykius** [theo-coder/vscode-open-folder#2]
Hi @theo-coder,

Great extension, I've been looking for it for long time!
I would like to suggest a new feature: it would be awesome to be able to open the selected folder (or file) without having to use the mouse to click the button. Do you think it is possible to add a keybinding (maybe configurable from the settings)?

I've never coded a vscode extension, but if you give me a couple of pointers I could try to prepare a PR.

Thanks!

**Comment by theo-coder** [comment]
Hi @lykius,

Just did a quick update to handle your request :)
v0.0.3 -> https://github.com/theo-coder/vscode-open-folder/commit/ea4a8195eb316699b4a47a38f8eb35b38dd65ae8

**Comment by lykius** [comment]
Pretty cool! Thanks!!!
